import type { N5Entry } from './types';

// JLPT 공식 목록 비공개 -> source 항상 'unofficial' (비공식 교재 기반).
// 여행 도메인과 겹치는 N5 핵심부터 채운다 — 커버리지 리포트: npm run report:n5
// id 규칙: 문법 n5_g_*, 어휘 n5_v_* (의미 slug), 한자 n5_k_* (의미 slug).
export const n5: N5Entry[] = [
  // ── 문법 (~40) — 정중형·조사·의문사·기본 패턴 ──────────────
  { id: 'n5_g_masu',           type: 'grammar', value: 'ます',           source: 'unofficial' },
  { id: 'n5_g_desu',           type: 'grammar', value: 'です',           source: 'unofficial' },
  { id: 'n5_g_masen',          type: 'grammar', value: 'ません',         source: 'unofficial' },
  { id: 'n5_g_mashita',        type: 'grammar', value: 'ました',         source: 'unofficial' },
  { id: 'n5_g_masenka',        type: 'grammar', value: 'ませんか',       source: 'unofficial' },
  { id: 'n5_g_mashou',         type: 'grammar', value: 'ましょう',       source: 'unofficial' },
  { id: 'n5_g_desuka',         type: 'grammar', value: 'ですか',         source: 'unofficial' },
  { id: 'n5_g_ja_arimasen',    type: 'grammar', value: 'じゃありません', source: 'unofficial' },
  { id: 'n5_g_te_kudasai',     type: 'grammar', value: 'てください',     source: 'unofficial' },
  { id: 'n5_g_naide_kudasai',  type: 'grammar', value: 'ないでください', source: 'unofficial' },
  { id: 'n5_g_tai',            type: 'grammar', value: 'たいです',       source: 'unofficial' },
  { id: 'n5_g_temo_ii',        type: 'grammar', value: 'てもいいですか', source: 'unofficial' },
  { id: 'n5_g_te_imasu',       type: 'grammar', value: 'ています',       source: 'unofficial' },
  { id: 'n5_g_kudasai',        type: 'grammar', value: 'ください',       source: 'unofficial' },
  { id: 'n5_g_onegai',         type: 'grammar', value: 'おねがいします', source: 'unofficial' },
  { id: 'n5_g_arimasu',        type: 'grammar', value: 'あります',       source: 'unofficial' },
  { id: 'n5_g_imasu',          type: 'grammar', value: 'います',         source: 'unofficial' },
  { id: 'n5_g_wa',             type: 'grammar', value: 'は(주제)',       reading: 'は', source: 'unofficial' },
  { id: 'n5_g_ga',             type: 'grammar', value: 'が(주어)',       reading: 'が', source: 'unofficial' },
  { id: 'n5_g_wo',             type: 'grammar', value: 'を(목적)',       reading: 'を', source: 'unofficial' },
  { id: 'n5_g_ni',             type: 'grammar', value: 'に(장소·시간)',  reading: 'に', source: 'unofficial' },
  { id: 'n5_g_de',             type: 'grammar', value: 'で(수단·장소)',  reading: 'で', source: 'unofficial' },
  { id: 'n5_g_he',             type: 'grammar', value: 'へ(방향)',       reading: 'へ', source: 'unofficial' },
  { id: 'n5_g_to',             type: 'grammar', value: 'と(와/과)',      reading: 'と', source: 'unofficial' },
  { id: 'n5_g_mo',             type: 'grammar', value: 'も(도)',         reading: 'も', source: 'unofficial' },
  { id: 'n5_g_no',             type: 'grammar', value: 'の(의)',         reading: 'の', source: 'unofficial' },
  { id: 'n5_g_kara',           type: 'grammar', value: 'から(부터)',     reading: 'から', source: 'unofficial' },
  { id: 'n5_g_made',           type: 'grammar', value: 'まで(까지)',     reading: 'まで', source: 'unofficial' },
  { id: 'n5_g_ka',             type: 'grammar', value: 'か(의문)',       reading: 'か', source: 'unofficial' },
  { id: 'n5_g_ne',             type: 'grammar', value: 'ね(확인)',       reading: 'ね', source: 'unofficial' },
  { id: 'n5_g_yo',             type: 'grammar', value: 'よ(전달)',       reading: 'よ', source: 'unofficial' },
  { id: 'n5_g_kosoado',        type: 'grammar', value: 'これ・それ・あれ', reading: 'これ', source: 'unofficial' },
  { id: 'n5_g_kono',           type: 'grammar', value: 'この・その・あの', reading: 'この', source: 'unofficial' },
  { id: 'n5_g_doko',           type: 'grammar', value: 'どこ',           source: 'unofficial' },
  { id: 'n5_g_nani',           type: 'grammar', value: 'なに/なん',      reading: 'なに', source: 'unofficial' },
  { id: 'n5_g_ikura',          type: 'grammar', value: 'いくら',         source: 'unofficial' },
  { id: 'n5_g_itsu',           type: 'grammar', value: 'いつ',           source: 'unofficial' },
  { id: 'n5_g_dare',           type: 'grammar', value: 'だれ',           source: 'unofficial' },
  { id: 'n5_g_dou',            type: 'grammar', value: 'どう',           source: 'unofficial' },
  { id: 'n5_g_counter_tsu',    type: 'grammar', value: '〜つ(개수)',     reading: 'ひとつ', source: 'unofficial' },
  { id: 'n5_g_josuushi',       type: 'grammar', value: '조수사(〜枚・〜本・〜人)', reading: 'まい', source: 'unofficial' },

  // ── 어휘 (~80) — 여행에서 실제로 마주치는 N5 핵심어 ──────────
  { id: 'n5_v_daijoubu',   type: 'vocab', value: '大丈夫',       reading: 'だいじょうぶ', source: 'unofficial' },
  { id: 'n5_v_mizu',       type: 'vocab', value: '水',           reading: 'みず', source: 'unofficial' },
  { id: 'n5_v_ocha',       type: 'vocab', value: 'お茶',         reading: 'おちゃ', source: 'unofficial' },
  { id: 'n5_v_eki',        type: 'vocab', value: '駅',           reading: 'えき', source: 'unofficial' },
  { id: 'n5_v_densha',     type: 'vocab', value: '電車',         reading: 'でんしゃ', source: 'unofficial' },
  { id: 'n5_v_basu',       type: 'vocab', value: 'バス',         source: 'unofficial' },
  { id: 'n5_v_takushii',   type: 'vocab', value: 'タクシー',     source: 'unofficial' },
  { id: 'n5_v_hikouki',    type: 'vocab', value: '飛行機',       reading: 'ひこうき', source: 'unofficial' },
  { id: 'n5_v_kuukou',     type: 'vocab', value: '空港',         reading: 'くうこう', source: 'unofficial' },
  { id: 'n5_v_kippu',      type: 'vocab', value: '切符',         reading: 'きっぷ', source: 'unofficial' },
  { id: 'n5_v_okane',      type: 'vocab', value: 'お金',         reading: 'おかね', source: 'unofficial' },
  { id: 'n5_v_en',         type: 'vocab', value: '円',           reading: 'えん', source: 'unofficial' },
  { id: 'n5_v_mise',       type: 'vocab', value: '店',           reading: 'みせ', source: 'unofficial' },
  { id: 'n5_v_ginkou',     type: 'vocab', value: '銀行',         reading: 'ぎんこう', source: 'unofficial' },
  { id: 'n5_v_byouin',     type: 'vocab', value: '病院',         reading: 'びょういん', source: 'unofficial' },
  { id: 'n5_v_kusuri',     type: 'vocab', value: '薬',           reading: 'くすり', source: 'unofficial' },
  { id: 'n5_v_hoteru',     type: 'vocab', value: 'ホテル',       source: 'unofficial' },
  { id: 'n5_v_heya',       type: 'vocab', value: '部屋',         reading: 'へや', source: 'unofficial' },
  { id: 'n5_v_toire',      type: 'vocab', value: 'トイレ',       source: 'unofficial' },
  { id: 'n5_v_resutoran',  type: 'vocab', value: 'レストラン',   source: 'unofficial' },
  { id: 'n5_v_asagohan',   type: 'vocab', value: '朝ごはん',     reading: 'あさごはん', source: 'unofficial' },
  { id: 'n5_v_hirugohan',  type: 'vocab', value: '昼ごはん',     reading: 'ひるごはん', source: 'unofficial' },
  { id: 'n5_v_bangohan',   type: 'vocab', value: '晩ごはん',     reading: 'ばんごはん', source: 'unofficial' },
  { id: 'n5_v_niku',       type: 'vocab', value: '肉',           reading: 'にく', source: 'unofficial' },
  { id: 'n5_v_sakana',     type: 'vocab', value: '魚',           reading: 'さかな', source: 'unofficial' },
  { id: 'n5_v_yasai',      type: 'vocab', value: '野菜',         reading: 'やさい', source: 'unofficial' },
  { id: 'n5_v_kudamono',   type: 'vocab', value: '果物',         reading: 'くだもの', source: 'unofficial' },
  { id: 'n5_v_tamago',     type: 'vocab', value: '卵',           reading: 'たまご', source: 'unofficial' },
  { id: 'n5_v_pan',        type: 'vocab', value: 'パン',         source: 'unofficial' },
  { id: 'n5_v_gyuunyuu',   type: 'vocab', value: '牛乳',         reading: 'ぎゅうにゅう', source: 'unofficial' },
  { id: 'n5_v_koohii',     type: 'vocab', value: 'コーヒー',     source: 'unofficial' },
  { id: 'n5_v_biiru',      type: 'vocab', value: 'ビール',       source: 'unofficial' },
  { id: 'n5_v_sake',       type: 'vocab', value: 'お酒',         reading: 'おさけ', source: 'unofficial' },
  { id: 'n5_v_hashi',      type: 'vocab', value: '箸',           reading: 'はし', source: 'unofficial' },
  { id: 'n5_v_migi',       type: 'vocab', value: '右',           reading: 'みぎ', source: 'unofficial' },
  { id: 'n5_v_hidari',     type: 'vocab', value: '左',           reading: 'ひだり', source: 'unofficial' },
  { id: 'n5_v_mae',        type: 'vocab', value: '前',           reading: 'まえ', source: 'unofficial' },
  { id: 'n5_v_ushiro',     type: 'vocab', value: '後ろ',         reading: 'うしろ', source: 'unofficial' },
  { id: 'n5_v_ue',         type: 'vocab', value: '上',           reading: 'うえ', source: 'unofficial' },
  { id: 'n5_v_shita',      type: 'vocab', value: '下',           reading: 'した', source: 'unofficial' },
  { id: 'n5_v_naka',       type: 'vocab', value: '中',           reading: 'なか', source: 'unofficial' },
  { id: 'n5_v_soto',       type: 'vocab', value: '外',           reading: 'そと', source: 'unofficial' },
  { id: 'n5_v_chikaku',    type: 'vocab', value: '近く',         reading: 'ちかく', source: 'unofficial' },
  { id: 'n5_v_tooi',       type: 'vocab', value: '遠い',         reading: 'とおい', source: 'unofficial' },
  { id: 'n5_v_ookii',      type: 'vocab', value: '大きい',       reading: 'おおきい', source: 'unofficial' },
  { id: 'n5_v_chiisai',    type: 'vocab', value: '小さい',       reading: 'ちいさい', source: 'unofficial' },
  { id: 'n5_v_takai',      type: 'vocab', value: '高い',         reading: 'たかい', source: 'unofficial' },
  { id: 'n5_v_yasui',      type: 'vocab', value: '安い',         reading: 'やすい', source: 'unofficial' },
  { id: 'n5_v_atarashii',  type: 'vocab', value: '新しい',       reading: 'あたらしい', source: 'unofficial' },
  { id: 'n5_v_furui',      type: 'vocab', value: '古い',         reading: 'ふるい', source: 'unofficial' },
  { id: 'n5_v_ii',         type: 'vocab', value: 'いい',         source: 'unofficial' },
  { id: 'n5_v_warui',      type: 'vocab', value: '悪い',         reading: 'わるい', source: 'unofficial' },
  { id: 'n5_v_atsui',      type: 'vocab', value: '暑い',         reading: 'あつい', source: 'unofficial' },
  { id: 'n5_v_samui',      type: 'vocab', value: '寒い',         reading: 'さむい', source: 'unofficial' },
  { id: 'n5_v_tsumetai',   type: 'vocab', value: '冷たい',       reading: 'つめたい', source: 'unofficial' },
  { id: 'n5_v_oishii',     type: 'vocab', value: 'おいしい',     source: 'unofficial' },
  { id: 'n5_v_iku',        type: 'vocab', value: '行く',         reading: 'いき', source: 'unofficial' },
  { id: 'n5_v_kuru',       type: 'vocab', value: '来る',         reading: 'き', source: 'unofficial' },
  { id: 'n5_v_kaeru',      type: 'vocab', value: '帰る',         reading: 'かえり', source: 'unofficial' },
  { id: 'n5_v_taberu',     type: 'vocab', value: '食べる',       reading: 'たべ', source: 'unofficial' },
  { id: 'n5_v_nomu',       type: 'vocab', value: '飲む',         reading: 'のみ', source: 'unofficial' },
  { id: 'n5_v_kau',        type: 'vocab', value: '買う',         reading: 'かい', source: 'unofficial' },
  { id: 'n5_v_miru',       type: 'vocab', value: '見る',         reading: 'み', source: 'unofficial' },
  { id: 'n5_v_kiku',       type: 'vocab', value: '聞く',         reading: 'きき', source: 'unofficial' },
  { id: 'n5_v_hanasu',     type: 'vocab', value: '話す',         reading: 'はなし', source: 'unofficial' },
  { id: 'n5_v_yomu',       type: 'vocab', value: '読む',         reading: 'よみ', source: 'unofficial' },
  { id: 'n5_v_kaku',       type: 'vocab', value: '書く',         reading: 'かき', source: 'unofficial' },
  { id: 'n5_v_matsu',      type: 'vocab', value: '待つ',         reading: 'まち', source: 'unofficial' },
  { id: 'n5_v_suwaru',     type: 'vocab', value: '座る',         reading: 'すわり', source: 'unofficial' },
  { id: 'n5_v_hairu',      type: 'vocab', value: '入る',         reading: 'はいり', source: 'unofficial' },
  { id: 'n5_v_deru',       type: 'vocab', value: '出る',         reading: 'で', source: 'unofficial' },
  { id: 'n5_v_noru',       type: 'vocab', value: '乗る',         reading: 'のり', source: 'unofficial' },
  { id: 'n5_v_oriru',      type: 'vocab', value: '降りる',       reading: 'おり', source: 'unofficial' },
  { id: 'n5_v_aruku',      type: 'vocab', value: '歩く',         reading: 'あるき', source: 'unofficial' },
  { id: 'n5_v_yasumu',     type: 'vocab', value: '休む',         reading: 'やすみ', source: 'unofficial' },
  { id: 'n5_v_wakaru',     type: 'vocab', value: '分かる',       reading: 'わかり', source: 'unofficial' },
  { id: 'n5_v_kyou',       type: 'vocab', value: '今日',         reading: 'きょう', source: 'unofficial' },
  { id: 'n5_v_ashita',     type: 'vocab', value: '明日',         reading: 'あした', source: 'unofficial' },
  { id: 'n5_v_kinou',      type: 'vocab', value: '昨日',         reading: 'きのう', source: 'unofficial' },
  { id: 'n5_v_ima',        type: 'vocab', value: '今',           reading: 'いま', source: 'unofficial' },
  { id: 'n5_v_jikan',      type: 'vocab', value: '時間',         reading: 'じかん', source: 'unofficial' },

  // ── 한자 (~20) — 표지·가격·시간에서 바로 마주치는 것 ─────────
  { id: 'n5_k_person',  type: 'kanji', value: '人', source: 'unofficial' },
  { id: 'n5_k_day',     type: 'kanji', value: '日', source: 'unofficial' },
  { id: 'n5_k_month',   type: 'kanji', value: '月', source: 'unofficial' },
  { id: 'n5_k_fire',    type: 'kanji', value: '火', source: 'unofficial' },
  { id: 'n5_k_water',   type: 'kanji', value: '水', source: 'unofficial' },
  { id: 'n5_k_tree',    type: 'kanji', value: '木', source: 'unofficial' },
  { id: 'n5_k_gold',    type: 'kanji', value: '金', source: 'unofficial' },
  { id: 'n5_k_earth',   type: 'kanji', value: '土', source: 'unofficial' },
  { id: 'n5_k_yen',     type: 'kanji', value: '円', source: 'unofficial' },
  { id: 'n5_k_time',    type: 'kanji', value: '時', source: 'unofficial' },
  { id: 'n5_k_minute',  type: 'kanji', value: '分', source: 'unofficial' },
  { id: 'n5_k_station', type: 'kanji', value: '駅', source: 'unofficial' },
  { id: 'n5_k_mouth',   type: 'kanji', value: '口', source: 'unofficial' },
  { id: 'n5_k_exit',    type: 'kanji', value: '出', source: 'unofficial' },
  { id: 'n5_k_enter',   type: 'kanji', value: '入', source: 'unofficial' },
  { id: 'n5_k_up',      type: 'kanji', value: '上', source: 'unofficial' },
  { id: 'n5_k_down',    type: 'kanji', value: '下', source: 'unofficial' },
  { id: 'n5_k_middle',  type: 'kanji', value: '中', source: 'unofficial' },
  { id: 'n5_k_big',     type: 'kanji', value: '大', source: 'unofficial' },
  { id: 'n5_k_small',   type: 'kanji', value: '小', source: 'unofficial' },
];
