// 단어 사용 예제 — 그 단어를 실제로 쓰게 되는 질문↔답변 한 쌍. "단어만 외우지 말고 예제로" 요청에 따라
// 학습 카드(IntroduceCard)에 덧붙는다. VOCAB_GROUPS 항목 id로 연결(greetingResponses.ts와 같은 패턴).
export interface VocabExample {
  questionJa: string;
  questionKana: string;
  questionKorean: string;
  answerJa: string;
  answerKana: string;
  answerKorean: string;
}

export const VOCAB_EXAMPLES: Record<string, VocabExample> = {
  // ── 기본 인사 ──────────────────────────────────────────
  g_ohayou: { questionJa: '朝、先生に会いました。', questionKana: 'あさ、せんせいにあいました。', questionKorean: '아침에 선생님을 만났어요.', answerJa: 'おはようございます。', answerKana: 'おはようございます。', answerKorean: '안녕하세요(아침 인사).' },
  g_konnichiwa: { questionJa: '昼、隣の人に会いました。', questionKana: 'ひる、となりのひとにあいました。', questionKorean: '낮에 옆집 사람을 만났어요.', answerJa: 'こんにちは。', answerKana: 'こんにちは。', answerKorean: '안녕하세요(낮 인사).' },
  g_konbanwa: { questionJa: '夜、店に入りました。', questionKana: 'よる、みせにはいりました。', questionKorean: '저녁에 가게에 들어갔어요.', answerJa: 'こんばんは。', answerKana: 'こんばんは。', answerKorean: '안녕하세요(저녁 인사).' },
  g_oyasumi: { questionJa: '寝る前、家族に言います。', questionKana: 'ねるまえ、かぞくにいいます。', questionKorean: '자기 전에 가족에게 말해요.', answerJa: 'おやすみなさい。', answerKana: 'おやすみなさい。', answerKorean: '잘 자요.' },
  g_arigatou: { questionJa: '店員さんが荷物を持ってくれました。', questionKana: 'てんいんさんがにもつをもってくれました。', questionKorean: '점원이 짐을 들어줬어요.', answerJa: 'ありがとうございます。', answerKana: 'ありがとうございます。', answerKorean: '감사합니다.' },
  g_sumimasen: { questionJa: '道で人にぶつかりました。', questionKana: 'みちでひとにぶつかりました。', questionKorean: '길에서 사람과 부딪혔어요.', answerJa: 'すみません。', answerKana: 'すみません。', answerKorean: '저기요 / 죄송합니다.' },
  g_gomen: { questionJa: '友達を待たせました。', questionKana: 'ともだちをまたせました。', questionKorean: '친구를 기다리게 했어요.', answerJa: 'ごめんなさい。', answerKana: 'ごめんなさい。', answerKorean: '미안합니다.' },
  g_douzo: { questionJa: 'お客さんが立っています。', questionKana: 'おきゃくさんがたっています。', questionKorean: '손님이 서 있어요.', answerJa: 'どうぞ、座ってください。', answerKana: 'どうぞ、すわってください。', answerKorean: '자, 어서 앉으세요.' },
  g_douitashimashite: { questionJa: 'ありがとうございます。', questionKana: 'ありがとうございます。', questionKorean: '감사합니다.', answerJa: 'どういたしまして。', answerKana: 'どういたしまして。', answerKorean: '천만에요.' },
  g_hajimemashite: { questionJa: '新しい同僚に会いました。', questionKana: 'あたらしいどうりょうにあいました。', questionKorean: '새 동료를 만났어요.', answerJa: 'はじめまして。', answerKana: 'はじめまして。', answerKorean: '처음 뵙겠습니다.' },
  g_yoroshiku: { questionJa: 'はじめまして。田中です。', questionKana: 'はじめまして。たなかです。', questionKorean: '처음 뵙겠습니다. 다나카입니다.', answerJa: 'よろしくお願いします。', answerKana: 'よろしくおねがいします。', answerKorean: '잘 부탁드립니다.' },
  g_sayonara: { questionJa: '先生の授業が終わりました。', questionKana: 'せんせいのじゅぎょうがおわりました。', questionKorean: '선생님 수업이 끝났어요.', answerJa: 'さようなら。', answerKana: 'さようなら。', answerKorean: '안녕히 계세요.' },
  g_mata_ne: { questionJa: '友達と別れます。', questionKana: 'ともだちとわかれます。', questionKorean: '친구와 헤어져요.', answerJa: 'またね。', answerKana: 'またね。', answerKorean: '또 봐요(캐주얼).' },
  g_ittekimasu: { questionJa: 'これから学校に行きます。', questionKana: 'これからがっこうにいきます。', questionKorean: '이제 학교에 가요.', answerJa: '行ってきます。', answerKana: 'いってきます。', answerKorean: '다녀오겠습니다.' },
  g_itterasshai: { questionJa: '行ってきます。', questionKana: 'いってきます。', questionKorean: '다녀오겠습니다.', answerJa: '行ってらっしゃい。', answerKana: 'いってらっしゃい。', answerKorean: '잘 다녀오세요.' },
  g_tadaima: { questionJa: '家に帰りました。', questionKana: 'いえにかえりました。', questionKorean: '집에 돌아왔어요.', answerJa: 'ただいま。', answerKana: 'ただいま。', answerKorean: '다녀왔습니다.' },
  g_okaerinasai: { questionJa: 'ただいま。', questionKana: 'ただいま。', questionKorean: '다녀왔습니다.', answerJa: 'おかえりなさい。', answerKana: 'おかえりなさい。', answerKorean: '어서 와요.' },
  g_otsukaresama: { questionJa: '仕事が終わりました。', questionKana: 'しごとがおわりました。', questionKorean: '일이 끝났어요.', answerJa: 'お疲れ様です。', answerKana: 'おつかれさまです。', answerKorean: '수고하셨습니다.' },

  // ── 신체 ──────────────────────────────────────────────
  b_atama: { questionJa: 'どこが痛いですか。', questionKana: 'どこがいたいですか。', questionKorean: '어디가 아파요?', answerJa: '頭が痛いです。', answerKana: 'あたまがいたいです。', answerKorean: '머리가 아파요.' },
  b_me: { questionJa: '疲れると、どこが痛いですか。', questionKana: 'つかれると、どこがいたいですか。', questionKorean: '피곤하면 어디가 아파요?', answerJa: '目が痛いです。', answerKana: 'めがいたいです。', answerKorean: '눈이 아파요.' },
  b_hana: { questionJa: '風邪の時、どこが辛いですか。', questionKana: 'かぜのとき、どこがつらいですか。', questionKorean: '감기 걸렸을 때 어디가 힘들어요?', answerJa: '鼻が辛いです。', answerKana: 'はながつらいです。', answerKorean: '코가 힘들어요.' },
  b_mimi: { questionJa: '音楽はどこで聞きますか。', questionKana: 'おんがくはどこでききますか。', questionKorean: '음악은 어디로 들어요?', answerJa: '耳で聞きます。', answerKana: 'みみでききます。', answerKorean: '귀로 들어요.' },
  b_kuchi: { questionJa: 'ご飯はどこで食べますか。', questionKana: 'ごはんはどこでたべますか。', questionKorean: '밥은 어디로 먹어요?', answerJa: '口で食べます。', answerKana: 'くちでたべます。', answerKorean: '입으로 먹어요.' },
  b_ha: { questionJa: '歯医者で何を見せますか。', questionKana: 'はいしゃでなにをみせますか。', questionKorean: '치과에서 뭘 보여줘요?', answerJa: '歯を見せます。', answerKana: 'はをみせます。', answerKorean: '치아를 보여줘요.' },
  b_nodo: { questionJa: '風邪の時、どこが痛いですか。', questionKana: 'かぜのとき、どこがいたいですか。', questionKorean: '감기 걸렸을 때 어디가 아파요?', answerJa: '喉が痛いです。', answerKana: 'のどがいたいです。', answerKorean: '목이 아파요.' },
  b_kata: { questionJa: '仕事の後、どこが凝りますか。', questionKana: 'しごとのあと、どこがこりますか。', questionKorean: '일 끝나고 어디가 뭉쳐요?', answerJa: '肩が凝ります。', answerKana: 'かたがこります。', answerKorean: '어깨가 뭉쳐요.' },
  b_mune: { questionJa: '手をどこに置きますか。', questionKana: 'てをどこにおきますか。', questionKorean: '손을 어디에 놓아요?', answerJa: '胸に置きます。', answerKana: 'むねにおきます。', answerKorean: '가슴에 놓아요.' },
  b_onaka: { questionJa: 'お腹すいた時、どこが鳴りますか。', questionKana: 'おなかすいたとき、どこがなりますか。', questionKorean: '배고플 때 어디서 소리가 나요?', answerJa: 'お腹が鳴ります。', answerKana: 'おなかがなります。', answerKorean: '배가 울려요.' },
  b_senaka: { questionJa: '長く座ると、どこが痛いですか。', questionKana: 'ながくすわると、どこがいたいですか。', questionKorean: '오래 앉으면 어디가 아파요?', answerJa: '背中が痛いです。', answerKana: 'せなかがいたいです。', answerKorean: '등이 아파요.' },
  b_te: { questionJa: '食事の前に何を洗いますか。', questionKana: 'しょくじのまえになにをあらいますか。', questionKorean: '식사 전에 뭘 씻어요?', answerJa: '手を洗います。', answerKana: 'てをあらいます。', answerKorean: '손을 씻어요.' },
  b_ude: { questionJa: '重い荷物はどこで持ちますか。', questionKana: 'おもいにもつはどこでもちますか。', questionKorean: '무거운 짐은 어디로 들어요?', answerJa: '腕で持ちます。', answerKana: 'うででもちます。', answerKorean: '팔로 들어요.' },
  b_yubi: { questionJa: '指輪はどこにつけますか。', questionKana: 'ゆびわはどこにつけますか。', questionKorean: '반지는 어디에 껴요?', answerJa: '指につけます。', answerKana: 'ゆびにつけます。', answerKorean: '손가락에 껴요.' },
  b_ashi: { questionJa: '靴はどこに履きますか。', questionKana: 'くつはどこにはきますか。', questionKorean: '신발은 어디에 신어요?', answerJa: '足に履きます。', answerKana: 'あしにはきます。', answerKorean: '발에 신어요.' },
  b_hiza: { questionJa: '階段で、どこが痛くなりますか。', questionKana: 'かいだんで、どこがいたくなりますか。', questionKorean: '계단에서 어디가 아파져요?', answerJa: '膝が痛くなります。', answerKana: 'ひざがいたくなります。', answerKorean: '무릎이 아파져요.' },
  b_karada: { questionJa: '運動すると、何が丈夫になりますか。', questionKana: 'うんどうすると、なにがじょうぶになりますか。', questionKorean: '운동하면 뭐가 튼튼해져요?', answerJa: '体が丈夫になります。', answerKana: 'からだがじょうぶになります。', answerKorean: '몸이 튼튼해져요.' },
  b_koshi: { questionJa: '重い物を持つと、どこが痛いですか。', questionKana: 'おもいものをもつと、どこがいたいですか。', questionKorean: '무거운 걸 들면 어디가 아파요?', answerJa: '腰が痛いです。', answerKana: 'こしがいたいです。', answerKorean: '허리가 아파요.' },

  // ── 운동·스포츠 ────────────────────────────────────────
  sp_sakka: { questionJa: '何のスポーツが好きですか。', questionKana: 'なんのスポーツがすきですか。', questionKorean: '무슨 운동을 좋아해요?', answerJa: 'サッカーが好きです。', answerKana: 'サッカーがすきです。', answerKorean: '축구를 좋아해요.' },
  sp_yakyu: { questionJa: '週末、何をしますか。', questionKana: 'しゅうまつ、なにをしますか。', questionKorean: '주말에 뭐 해요?', answerJa: '野球をします。', answerKana: 'やきゅうをします。', answerKorean: '야구를 해요.' },
  sp_tennis: { questionJa: '何のスポーツが得意ですか。', questionKana: 'なんのスポーツがとくいですか。', questionKorean: '무슨 운동을 잘해요?', answerJa: 'テニスが得意です。', answerKana: 'テニスがとくいです。', answerKorean: '테니스를 잘해요.' },
  sp_baske: { questionJa: '背が高いですね。何をしますか。', questionKana: 'せがたかいですね。なにをしますか。', questionKorean: '키가 크네요. 뭐 해요?', answerJa: 'バスケットボールをします。', answerKana: 'バスケットボールをします。', answerKorean: '농구를 해요.' },
  sp_volleyball: { questionJa: '学校で何のクラブに入っていますか。', questionKana: 'がっこうでなんのクラブにはいっていますか。', questionKorean: '학교에서 무슨 동아리에 있어요?', answerJa: 'バレーボール部です。', answerKana: 'バレーボールぶです。', answerKorean: '배구부예요.' },
  sp_suiei: { questionJa: '夏はよく何をしますか。', questionKana: 'なつはよくなにをしますか。', questionKorean: '여름엔 뭘 자주 해요?', answerJa: '水泳をします。', answerKana: 'すいえいをします。', answerKorean: '수영을 해요.' },
  sp_golf: { questionJa: '週末、お父さんは何をしますか。', questionKana: 'しゅうまつ、おとうさんはなにをしますか。', questionKorean: '주말에 아버지는 뭐 하세요?', answerJa: 'ゴルフをします。', answerKana: 'ゴルフをします。', answerKorean: '골프를 쳐요.' },
  sp_judo: { questionJa: '何の武道を習っていますか。', questionKana: 'なんのぶどうをならっていますか。', questionKorean: '무슨 무도를 배워요?', answerJa: '柔道を習っています。', answerKana: 'じゅうどうをならっています。', answerKorean: '유도를 배워요.' },
  sp_karate: { questionJa: '日本で何を習いたいですか。', questionKana: 'にほんでなにをならいたいですか。', questionKorean: '일본에서 뭘 배우고 싶어요?', answerJa: '空手を習いたいです。', answerKana: 'からてをならいたいです。', answerKorean: '가라테를 배우고 싶어요.' },
  sp_kendo: { questionJa: '剣を使うスポーツは何ですか。', questionKana: 'けんをつかうスポーツはなんですか。', questionKorean: '검을 쓰는 운동은 뭐예요?', answerJa: '剣道です。', answerKana: 'けんどうです。', answerKorean: '검도예요.' },
  sp_taiso: { questionJa: '朝、何をしますか。', questionKana: 'あさ、なにをしますか。', questionKorean: '아침에 뭐 해요?', answerJa: '体操をします。', answerKana: 'たいそうをします。', answerKorean: '체조를 해요.' },
  sp_marathon: { questionJa: '今度の大会は何ですか。', questionKana: 'こんどのたいかいはなんですか。', questionKorean: '이번 대회는 뭐예요?', answerJa: 'マラソンです。', answerKana: 'マラソンです。', answerKorean: '마라톤이에요.' },
  sp_cycling: { questionJa: '休みの日、何をしますか。', questionKana: 'やすみのひ、なにをしますか。', questionKorean: '쉬는 날 뭐 해요?', answerJa: 'サイクリングをします。', answerKana: 'サイクリングをします。', answerKorean: '사이클링을 해요.' },
  sp_yoga: { questionJa: '毎朝、何をしますか。', questionKana: 'まいあさ、なにをしますか。', questionKorean: '매일 아침 뭐 해요?', answerJa: 'ヨガをします。', answerKana: 'ヨガをします。', answerKorean: '요가를 해요.' },
  sp_skiing: { questionJa: '冬は何をしに行きますか。', questionKana: 'ふゆはなにをしにいきますか。', questionKorean: '겨울엔 뭘 하러 가요?', answerJa: 'スキーをしに行きます。', answerKana: 'スキーをしにいきます。', answerKorean: '스키 타러 가요.' },

  // ── 동물 ──────────────────────────────────────────────
  a_inu: { questionJa: 'あの動物は何ですか。', questionKana: 'あのどうぶつはなんですか。', questionKorean: '저 동물은 뭐예요?', answerJa: '犬です。', answerKana: 'いぬです。', answerKorean: '개예요.' },
  a_neko: { questionJa: '家で何を飼っていますか。', questionKana: 'いえでなにをかっていますか。', questionKorean: '집에서 뭘 키워요?', answerJa: '猫を飼っています。', answerKana: 'ねこをかっています。', answerKorean: '고양이를 키워요.' },
  a_tori: { questionJa: '空に何がいますか。', questionKana: 'そらになにがいますか。', questionKorean: '하늘에 뭐가 있어요?', answerJa: '鳥がいます。', answerKana: 'とりがいます。', answerKorean: '새가 있어요.' },
  a_sakana: { questionJa: '海に何がいますか。', questionKana: 'うみになにがいますか。', questionKorean: '바다에 뭐가 있어요?', answerJa: '魚がいます。', answerKana: 'さかながいます。', answerKorean: '물고기가 있어요.' },
  a_ushi: { questionJa: '牧場にどんな動物がいますか。', questionKana: 'ぼくじょうにどんなどうぶつがいますか。', questionKorean: '목장에 어떤 동물이 있어요?', answerJa: '牛がいます。', answerKana: 'うしがいます。', answerKorean: '소가 있어요.' },
  a_uma: { questionJa: '公園で何に乗りますか。', questionKana: 'こうえんでなににのりますか。', questionKorean: '공원에서 뭘 타요?', answerJa: '馬に乗ります。', answerKana: 'うまにのります。', answerKorean: '말을 타요.' },
  a_buta: { questionJa: '農場にどんな動物がいますか。', questionKana: 'のうじょうにどんなどうぶつがいますか。', questionKorean: '농장에 어떤 동물이 있어요?', answerJa: '豚がいます。', answerKana: 'ぶたがいます。', answerKorean: '돼지가 있어요.' },
  a_usagi: { questionJa: '耳が長い動物は何ですか。', questionKana: 'みみがながいどうぶつはなんですか。', questionKorean: '귀가 긴 동물은 뭐예요?', answerJa: '兎です。', answerKana: 'うさぎです。', answerKorean: '토끼예요.' },
  a_kuma: { questionJa: '山で危ない動物は何ですか。', questionKana: 'やまであぶないどうぶつはなんですか。', questionKorean: '산에서 위험한 동물은 뭐예요?', answerJa: '熊です。', answerKana: 'くまです。', answerKorean: '곰이에요.' },
  a_saru: { questionJa: '木に何がいますか。', questionKana: 'きになにがいますか。', questionKorean: '나무에 뭐가 있어요?', answerJa: '猿がいます。', answerKana: 'さるがいます。', answerKorean: '원숭이가 있어요.' },
  a_kirin: { questionJa: '動物園で一番背が高い動物は何ですか。', questionKana: 'どうぶつえんでいちばんせがたかいどうぶつはなんですか。', questionKorean: '동물원에서 제일 키 큰 동물은 뭐예요?', answerJa: 'キリンです。', answerKana: 'キリンです。', answerKorean: '기린이에요.' },
  a_zou: { questionJa: '鼻が長い動物は何ですか。', questionKana: 'はながながいどうぶつはなんですか。', questionKorean: '코가 긴 동물은 뭐예요?', answerJa: '象です。', answerKana: 'ぞうです。', answerKorean: '코끼리예요.' },
  a_rion: { questionJa: '動物の王様は何ですか。', questionKana: 'どうぶつのおうさまはなんですか。', questionKorean: '동물의 왕은 뭐예요?', answerJa: 'ライオンです。', answerKana: 'ライオンです。', answerKorean: '사자예요.' },
  a_hebi: { questionJa: '足がない動物は何ですか。', questionKana: 'あしがないどうぶつはなんですか。', questionKorean: '다리가 없는 동물은 뭐예요?', answerJa: '蛇です。', answerKana: 'へびです。', answerKorean: '뱀이에요.' },
  a_kame: { questionJa: 'ゆっくり歩く動物は何ですか。', questionKana: 'ゆっくりあるくどうぶつはなんですか。', questionKorean: '천천히 걷는 동물은 뭐예요?', answerJa: '亀です。', answerKana: 'かめです。', answerKorean: '거북이예요.' },
  ani_101: { questionJa: '白くて、もこもこの動物は何ですか。', questionKana: 'しろくて、もこもこのどうぶつはなんですか。', questionKorean: '하얗고 폭신한 동물은 뭐예요?', answerJa: '羊です。', answerKana: 'ひつじです。', answerKorean: '양이에요.' },
  ani_102: { questionJa: '尻尾が大きい動物は何ですか。', questionKana: 'しっぽがおおきいどうぶつはなんですか。', questionKorean: '꼬리가 큰 동물은 뭐예요?', answerJa: '狐です。', answerKana: 'きつねです。', answerKorean: '여우예요.' },
  ani_103: { questionJa: '池で鳴いている動物は何ですか。', questionKana: 'いけでないているどうぶつはなんですか。', questionKorean: '연못에서 우는 동물은 뭐예요?', answerJa: '蛙です。', answerKana: 'かえるです。', answerKorean: '개구리예요.' },
  ani_104: { questionJa: '縞模様の動物は何ですか。', questionKana: 'しまもようのどうぶつはなんですか。', questionKorean: '줄무늬 동물은 뭐예요?', answerJa: '虎です。', answerKana: 'とらです。', answerKorean: '호랑이예요.' },
  ani_105: { questionJa: '白黒で、竹を食べる動物は何ですか。', questionKana: 'しろくろで、たけをたべるどうぶつはなんですか。', questionKorean: '흑백에 대나무 먹는 동물은 뭐예요?', answerJa: 'パンダです。', answerKana: 'パンダです。', answerKorean: '판다예요.' },
  ani_106: { questionJa: '小さくて速い動物は何ですか。', questionKana: 'ちいさくてはやいどうぶつはなんですか。', questionKorean: '작고 빠른 동물은 뭐예요?', answerJa: '鼠です。', answerKana: 'ねずみです。', answerKorean: '쥐예요.' },

  // ── 식물·자연 ──────────────────────────────────────────
  pl_hana: { questionJa: '公園に何が咲いていますか。', questionKana: 'こうえんになにがさいていますか。', questionKorean: '공원에 뭐가 피어 있어요?', answerJa: '花が咲いています。', answerKana: 'はながさいています。', answerKorean: '꽃이 피어 있어요.' },
  pl_ki: { questionJa: '庭に何がありますか。', questionKana: 'にわになにがありますか。', questionKorean: '정원에 뭐가 있어요?', answerJa: '木があります。', answerKana: 'きがあります。', answerKorean: '나무가 있어요.' },
  pl_kusa: { questionJa: '公園の地面に何がありますか。', questionKana: 'こうえんのじめんになにがありますか。', questionKorean: '공원 땅에 뭐가 있어요?', answerJa: '草があります。', answerKana: 'くさがあります。', answerKorean: '풀이 있어요.' },
  pl_sakura: { questionJa: '春に何が咲きますか。', questionKana: 'はるになにがさきますか。', questionKorean: '봄에 뭐가 피어요?', answerJa: '桜が咲きます。', answerKana: 'さくらがさきます。', answerKorean: '벚꽃이 피어요.' },
  pl_take: { questionJa: 'パンダは何を食べますか。', questionKana: 'パンダはなにをたべますか。', questionKorean: '판다는 뭘 먹어요?', answerJa: '竹を食べます。', answerKana: 'たけをたべます。', answerKorean: '대나무를 먹어요.' },
  pl_matsu: { questionJa: 'お正月に飾る木は何ですか。', questionKana: 'おしょうがつにかざるきはなんですか。', questionKorean: '설날에 장식하는 나무는 뭐예요?', answerJa: '松です。', answerKana: 'まつです。', answerKorean: '소나무예요.' },
  pl_ume: { questionJa: '冬の終わりに何が咲きますか。', questionKana: 'ふゆのおわりになにがさきますか。', questionKorean: '겨울 끝에 뭐가 피어요?', answerJa: '梅が咲きます。', answerKana: 'うめがさきます。', answerKorean: '매화가 피어요.' },
  pl_mori: { questionJa: '木がたくさんある所は何ですか。', questionKana: 'きがたくさんあるところはなんですか。', questionKorean: '나무가 많은 곳은 뭐예요?', answerJa: '森です。', answerKana: 'もりです。', answerKorean: '숲이에요.' },
  pl_yama: { questionJa: '登山、どこに行きますか。', questionKana: 'とざん、どこにいきますか。', questionKorean: '등산, 어디로 가요?', answerJa: '山に行きます。', answerKana: 'やまにいきます。', answerKorean: '산에 가요.' },
  pl_kawa: { questionJa: '町の真ん中に何が流れていますか。', questionKana: 'まちのまんなかになにがながれていますか。', questionKorean: '마을 한가운데에 뭐가 흘러요?', answerJa: '川が流れています。', answerKana: 'かわがながれています。', answerKorean: '강이 흘러요.' },
  pl_umi: { questionJa: '夏、どこに泳ぎに行きますか。', questionKana: 'なつ、どこにおよぎにいきますか。', questionKorean: '여름에 어디로 수영하러 가요?', answerJa: '海に行きます。', answerKana: 'うみにいきます。', answerKorean: '바다에 가요.' },
  pl_sora: { questionJa: '鳥はどこを飛びますか。', questionKana: 'とりはどこをとびますか。', questionKorean: '새는 어디를 날아요?', answerJa: '空を飛びます。', answerKana: 'そらをとびます。', answerKorean: '하늘을 날아요.' },
  pl_tsuki: { questionJa: '夜、空に何が見えますか。', questionKana: 'よる、そらになにがみえますか。', questionKorean: '밤에 하늘에 뭐가 보여요?', answerJa: '月が見えます。', answerKana: 'つきがみえます。', answerKorean: '달이 보여요.' },
  pl_hoshi: { questionJa: '夜空にたくさん何がありますか。', questionKana: 'よぞらにたくさんなにがありますか。', questionKorean: '밤하늘에 뭐가 많아요?', answerJa: '星があります。', answerKana: 'ほしがあります。', answerKorean: '별이 많아요.' },
  pl_taiyou: { questionJa: '昼、空に何がありますか。', questionKana: 'ひる、そらになにがありますか。', questionKorean: '낮에 하늘에 뭐가 있어요?', answerJa: '太陽があります。', answerKana: 'たいようがあります。', answerKorean: '태양이 있어요.' },

  // ── 색깔 ──────────────────────────────────────────────
  c_aka: { questionJa: 'そのりんごは何色ですか。', questionKana: 'そのりんごはなにいろですか。', questionKorean: '그 사과는 무슨 색이에요?', answerJa: '赤です。', answerKana: 'あかです。', answerKorean: '빨간색이에요.' },
  c_ao: { questionJa: '空は何色ですか。', questionKana: 'そらはなにいろですか。', questionKorean: '하늘은 무슨 색이에요?', answerJa: '青です。', answerKana: 'あおです。', answerKorean: '파란색이에요.' },
  c_ki: { questionJa: 'バナナは何色ですか。', questionKana: 'バナナはなにいろですか。', questionKorean: '바나나는 무슨 색이에요?', answerJa: '黄色です。', answerKana: 'きいろです。', answerKorean: '노란색이에요.' },
  c_midori: { questionJa: '葉っぱは何色ですか。', questionKana: 'はっぱはなにいろですか。', questionKorean: '나뭇잎은 무슨 색이에요?', answerJa: '緑です。', answerKana: 'みどりです。', answerKorean: '초록색이에요.' },
  c_shiro: { questionJa: '雪は何色ですか。', questionKana: 'ゆきはなにいろですか。', questionKorean: '눈은 무슨 색이에요?', answerJa: '白です。', answerKana: 'しろです。', answerKorean: '흰색이에요.' },
  c_kuro: { questionJa: '夜の空は何色ですか。', questionKana: 'よるのそらはなにいろですか。', questionKorean: '밤하늘은 무슨 색이에요?', answerJa: '黒です。', answerKana: 'くろです。', answerKorean: '검은색이에요.' },
  c_cha: { questionJa: 'コーヒーは何色ですか。', questionKana: 'コーヒーはなにいろですか。', questionKorean: '커피는 무슨 색이에요?', answerJa: '茶色です。', answerKana: 'ちゃいろです。', answerKorean: '갈색이에요.' },
  c_murasaki: { questionJa: 'なすは何色ですか。', questionKana: 'なすはなにいろですか。', questionKorean: '가지는 무슨 색이에요?', answerJa: '紫です。', answerKana: 'むらさきです。', answerKorean: '보라색이에요.' },
  c_orange: { questionJa: 'みかんは何色ですか。', questionKana: 'みかんはなにいろですか。', questionKorean: '귤은 무슨 색이에요?', answerJa: 'オレンジです。', answerKana: 'オレンジです。', answerKorean: '주황색이에요.' },
  c_pink: { questionJa: '桜は何色ですか。', questionKana: 'さくらはなにいろですか。', questionKorean: '벚꽃은 무슨 색이에요?', answerJa: 'ピンクです。', answerKana: 'ピンクです。', answerKorean: '분홍색이에요.' },
  c_haiiro: { questionJa: '雨の日の空は何色ですか。', questionKana: 'あめのひのそらはなにいろですか。', questionKorean: '비 오는 날 하늘은 무슨 색이에요?', answerJa: '灰色です。', answerKana: 'はいいろです。', answerKorean: '회색이에요.' },
  c_kiniro: { questionJa: 'メダルは何色ですか。', questionKana: 'メダルはなにいろですか。', questionKorean: '메달은 무슨 색이에요?', answerJa: '金色です。', answerKana: 'きんいろです。', answerKorean: '금색이에요.' },
  col_101: { questionJa: '晴れた日の空は何色ですか。', questionKana: 'はれたひのそらはなにいろですか。', questionKorean: '맑은 날 하늘은 무슨 색이에요?', answerJa: '水色です。', answerKana: 'みずいろです。', answerKorean: '하늘색이에요.' },
  col_102: { questionJa: '制服は何色ですか。', questionKana: 'せいふくはなにいろですか。', questionKorean: '교복은 무슨 색이에요?', answerJa: '紺色です。', answerKana: 'こんいろです。', answerKorean: '남색이에요.' },
  col_103: { questionJa: '2位のメダルは何色ですか。', questionKana: 'にいのメダルはなにいろですか。', questionKorean: '2등 메달은 무슨 색이에요?', answerJa: '銀色です。', answerKana: 'ぎんいろです。', answerKorean: '은색이에요.' },

  // ── 음식·식재료 ────────────────────────────────────────
  f_gohan: { questionJa: '朝、何を食べましたか。', questionKana: 'あさ、なにをたべましたか。', questionKorean: '아침에 뭘 먹었어요?', answerJa: 'ご飯を食べました。', answerKana: 'ごはんをたべました。', answerKorean: '밥을 먹었어요.' },
  f_pan: { questionJa: '朝ご飯に何を食べますか。', questionKana: 'あさごはんになにをたべますか。', questionKorean: '아침에 뭘 먹어요?', answerJa: 'パンを食べます。', answerKana: 'パンをたべます。', answerKorean: '빵을 먹어요.' },
  f_niku: { questionJa: '焼肉屋で何を食べますか。', questionKana: 'やきにくやでなにをたべますか。', questionKorean: '고깃집에서 뭘 먹어요?', answerJa: '肉を食べます。', answerKana: 'にくをたべます。', answerKorean: '고기를 먹어요.' },
  f_sakana2: { questionJa: '寿司屋で何を食べますか。', questionKana: 'すしやでなにをたべますか。', questionKorean: '초밥집에서 뭘 먹어요?', answerJa: '魚を食べます。', answerKana: 'さかなをたべます。', answerKorean: '생선을 먹어요.' },
  f_yasai: { questionJa: '健康のために何を食べますか。', questionKana: 'けんこうのためになにをたべますか。', questionKorean: '건강을 위해 뭘 먹어요?', answerJa: '野菜を食べます。', answerKana: 'やさいをたべます。', answerKorean: '채소를 먹어요.' },
  f_kudamono: { questionJa: 'デザートに何を食べますか。', questionKana: 'デザートになにをたべますか。', questionKorean: '디저트로 뭘 먹어요?', answerJa: '果物を食べます。', answerKana: 'くだものをたべます。', answerKorean: '과일을 먹어요.' },
  f_tamago: { questionJa: '朝ご飯に何を焼きますか。', questionKana: 'あさごはんになにをやきますか。', questionKorean: '아침으로 뭘 부쳐요?', answerJa: '卵を焼きます。', answerKana: 'たまごをやきます。', answerKorean: '달걀을 부쳐요.' },
  f_mizu: { questionJa: '何が飲みたいですか。', questionKana: 'なにがのみたいですか。', questionKorean: '뭐 마시고 싶어요?', answerJa: '水が飲みたいです。', answerKana: 'みずがのみたいです。', answerKorean: '물이 마시고 싶어요.' },
  f_ocha: { questionJa: '食後、何を飲みますか。', questionKana: 'しょくご、なにをのみますか。', questionKorean: '식후에 뭘 마셔요?', answerJa: 'お茶を飲みます。', answerKana: 'おちゃをのみます。', answerKorean: '차를 마셔요.' },
  f_koohii: { questionJa: '朝、何を飲みますか。', questionKana: 'あさ、なにをのみますか。', questionKorean: '아침에 뭘 마셔요?', answerJa: 'コーヒーを飲みます。', answerKana: 'コーヒーをのみます。', answerKorean: '커피를 마셔요.' },
  f_biiru: { questionJa: '夕食の時、何を飲みますか。', questionKana: 'ゆうしょくのとき、なにをのみますか。', questionKorean: '저녁 식사 때 뭘 마셔요?', answerJa: 'ビールを飲みます。', answerKana: 'ビールをのみます。', answerKorean: '맥주를 마셔요.' },
  f_sake: { questionJa: '居酒屋で何を飲みますか。', questionKana: 'いざかやでなにをのみますか。', questionKorean: '이자카야에서 뭘 마셔요?', answerJa: 'お酒を飲みます。', answerKana: 'おさけをのみます。', answerKorean: '술을 마셔요.' },
  f_sushi: { questionJa: '何が食べたいですか。', questionKana: 'なにがたべたいですか。', questionKorean: '뭐 먹고 싶어요?', answerJa: '寿司が食べたいです。', answerKana: 'すしがたべたいです。', answerKorean: '초밥이 먹고 싶어요.' },
  f_ramen: { questionJa: '昼、何を食べますか。', questionKana: 'ひる、なにをたべますか。', questionKorean: '점심에 뭘 먹어요?', answerJa: 'ラーメンを食べます。', answerKana: 'ラーメンをたべます。', answerKorean: '라멘을 먹어요.' },
  f_soba: { questionJa: '年越しに何を食べますか。', questionKana: 'としこしになにをたべますか。', questionKorean: '연말에 뭘 먹어요?', answerJa: 'そばを食べます。', answerKana: 'そばをたべます。', answerKorean: '소바를 먹어요.' },
  f_tempura: { questionJa: 'この店の人気メニューは何ですか。', questionKana: 'このみせのにんきメニューはなんですか。', questionKorean: '이 가게 인기 메뉴는 뭐예요?', answerJa: '天ぷらです。', answerKana: 'てんぷらです。', answerKorean: '텐푸라예요.' },
  f_karaage: { questionJa: '居酒屋で何を頼みますか。', questionKana: 'いざかやでなにをたのみますか。', questionKorean: '이자카야에서 뭘 시켜요?', answerJa: '唐揚げを頼みます。', answerKana: 'からあげをたのみます。', answerKorean: '가라아게를 시켜요.' },
  f_onigiri: { questionJa: 'コンビニで何を買いますか。', questionKana: 'コンビニでなにをかいますか。', questionKorean: '편의점에서 뭘 사요?', answerJa: 'おにぎりを買います。', answerKana: 'おにぎりをかいます。', answerKorean: '주먹밥을 사요.' },
  food_101: { questionJa: '寒い日、何を食べたいですか。', questionKana: 'さむいひ、なにをたべたいですか。', questionKorean: '추운 날 뭐 먹고 싶어요?', answerJa: 'うどんが食べたいです。', answerKana: 'うどんがたべたいです。', answerKorean: '우동이 먹고 싶어요.' },
  food_102: { questionJa: '今日の晩ご飯は何ですか。', questionKana: 'きょうのばんごはんはなんですか。', questionKorean: '오늘 저녁은 뭐예요?', answerJa: 'カレーです。', answerKana: 'カレーです。', answerKorean: '카레예요.' },
  food_103: { questionJa: '中華料理で何を頼みますか。', questionKana: 'ちゅうかりょうりでなにをたのみますか。', questionKorean: '중화요리에서 뭘 시켜요?', answerJa: '餃子を頼みます。', answerKana: 'ぎょうざをたのみます。', answerKorean: '만두를 시켜요.' },
  food_104: { questionJa: '居酒屋の名物は何ですか。', questionKana: 'いざかやのめいぶつはなんですか。', questionKorean: '이자카야 명물은 뭐예요?', answerJa: '焼き鳥です。', answerKana: 'やきとりです。', answerKorean: '야키토리예요.' },
  food_105: { questionJa: '定食屋で何を注文しますか。', questionKana: 'ていしょくやでなにをちゅうもんしますか。', questionKorean: '정식집에서 뭘 주문해요?', answerJa: 'とんかつを注文します。', answerKana: 'とんかつをちゅうもんします。', answerKorean: '돈카츠를 주문해요.' },
  food_106: { questionJa: '誕生日に何を食べますか。', questionKana: 'たんじょうびになにをたべますか。', questionKorean: '생일에 뭘 먹어요?', answerJa: 'ケーキを食べます。', answerKana: 'ケーキをたべます。', answerKorean: '케이크를 먹어요.' },
  food_107: { questionJa: '夏に何が食べたいですか。', questionKana: 'なつになにがたべたいですか。', questionKorean: '여름에 뭐 먹고 싶어요?', answerJa: 'アイスが食べたいです。', answerKana: 'アイスがたべたいです。', answerKorean: '아이스크림이 먹고 싶어요.' },
  food_108: { questionJa: 'ダイエット中、何を食べますか。', questionKana: 'ダイエットちゅう、なにをたべますか。', questionKorean: '다이어트 중에 뭘 먹어요?', answerJa: 'サラダを食べます。', answerKana: 'サラダをたべます。', answerKorean: '샐러드를 먹어요.' },
  food_109: { questionJa: '何時に朝ご飯を食べますか。', questionKana: 'なんじにあさごはんをたべますか。', questionKorean: '몇 시에 아침밥을 먹어요?', answerJa: '七時に朝ご飯を食べます。', answerKana: 'しちじにあさごはんをたべます。', answerKorean: '7시에 아침밥을 먹어요.' },
  food_110: { questionJa: '昼ご飯はどこで食べますか。', questionKana: 'ひるごはんはどこでたべますか。', questionKorean: '점심밥은 어디서 먹어요?', answerJa: '会社で昼ご飯を食べます。', answerKana: 'かいしゃでひるごはんをたべます。', answerKorean: '회사에서 점심밥을 먹어요.' },
  food_111: { questionJa: '家族と何を食べますか。', questionKana: 'かぞくとなにをたべますか。', questionKorean: '가족이랑 뭘 먹어요?', answerJa: '晩ご飯を食べます。', answerKana: 'ばんごはんをたべます。', answerKorean: '저녁밥을 먹어요.' },
  food_112: { questionJa: '朝、何を飲みますか。', questionKana: 'あさ、なにをのみますか。', questionKorean: '아침에 뭘 마셔요?', answerJa: '牛乳を飲みます。', answerKana: 'ぎゅうにゅうをのみます。', answerKorean: '우유를 마셔요.' },

  // ── 가족 ──────────────────────────────────────────────
  fam_chichi: { questionJa: 'これは誰ですか。', questionKana: 'これはだれですか。', questionKorean: '이 사람은 누구예요?', answerJa: '父です。', answerKana: 'ちちです。', answerKorean: '(제) 아버지예요.' },
  fam_haha: { questionJa: '料理が上手なのは誰ですか。', questionKana: 'りょうりがじょうずなのはだれですか。', questionKorean: '요리 잘하는 사람은 누구예요?', answerJa: '母です。', answerKana: 'ははです。', answerKorean: '(제) 어머니예요.' },
  fam_ani: { questionJa: 'あなたより年上の男の兄弟は誰ですか。', questionKana: 'あなたよりとしうえのおとこのきょうだいはだれですか。', questionKorean: '당신보다 나이 많은 남자 형제는 누구예요?', answerJa: '兄です。', answerKana: 'あにです。', answerKorean: '(제) 오빠/형이에요.' },
  fam_ane: { questionJa: 'あなたより年上の女の兄弟は誰ですか。', questionKana: 'あなたよりとしうえのおんなのきょうだいはだれですか。', questionKorean: '당신보다 나이 많은 여자 형제는 누구예요?', answerJa: '姉です。', answerKana: 'あねです。', answerKorean: '(제) 언니/누나예요.' },
  fam_otouto: { questionJa: 'あなたより年下の男の兄弟は誰ですか。', questionKana: 'あなたよりとししたのおとこのきょうだいはだれですか。', questionKorean: '당신보다 어린 남자 형제는 누구예요?', answerJa: '弟です。', answerKana: 'おとうとです。', answerKorean: '남동생이에요.' },
  fam_imouto: { questionJa: 'あなたより年下の女の兄弟は誰ですか。', questionKana: 'あなたよりとししたのおんなのきょうだいはだれですか。', questionKorean: '당신보다 어린 여자 형제는 누구예요?', answerJa: '妹です。', answerKana: 'いもうとです。', answerKorean: '여동생이에요.' },
  fam_musuko: { questionJa: 'あの男の子は誰ですか。', questionKana: 'あのおとこのこはだれですか。', questionKorean: '저 남자아이는 누구예요?', answerJa: '息子です。', answerKana: 'むすこです。', answerKorean: '(제) 아들이에요.' },
  fam_musume: { questionJa: 'あの女の子は誰ですか。', questionKana: 'あのおんなのこはだれですか。', questionKorean: '저 여자아이는 누구예요?', answerJa: '娘です。', answerKana: 'むすめです。', answerKorean: '(제) 딸이에요.' },
  fam_otto: { questionJa: 'あの人は誰ですか。', questionKana: 'あのひとはだれですか。', questionKorean: '저 사람은 누구예요?', answerJa: '夫です。', answerKana: 'おっとです。', answerKorean: '(제) 남편이에요.' },
  fam_tsuma: { questionJa: 'あの人は誰ですか。', questionKana: 'あのひとはだれですか。', questionKorean: '저 사람은 누구예요?', answerJa: '妻です。', answerKana: 'つまです。', answerKorean: '(제) 아내예요.' },
  fam_kazoku: { questionJa: '週末、誰と過ごしますか。', questionKana: 'しゅうまつ、だれとすごしますか。', questionKorean: '주말에 누구랑 지내요?', answerJa: '家族と過ごします。', answerKana: 'かぞくとすごします。', answerKorean: '가족이랑 지내요.' },
  fam_tomodachi: { questionJa: '誰と旅行しますか。', questionKana: 'だれとりょこうしますか。', questionKorean: '누구랑 여행 가요?', answerJa: '友達と旅行します。', answerKana: 'ともだちとりょこうします。', answerKorean: '친구랑 여행 가요.' },

  // ── 날씨 ──────────────────────────────────────────────
  w_hare: { questionJa: '今日の天気はどうですか。', questionKana: 'きょうのてんきはどうですか。', questionKorean: '오늘 날씨 어때요?', answerJa: '晴れです。', answerKana: 'はれです。', answerKorean: '맑아요.' },
  w_kumori: { questionJa: '明日の天気はどうですか。', questionKana: 'あしたのてんきはどうですか。', questionKorean: '내일 날씨 어때요?', answerJa: '曇りです。', answerKana: 'くもりです。', answerKorean: '흐려요.' },
  w_ame: { questionJa: '傘を持って行きますか。', questionKana: 'かさをもっていきますか。', questionKorean: '우산 가져가요?', answerJa: 'はい、雨です。', answerKana: 'はい、あめです。', answerKorean: '네, 비 와요.' },
  w_yuki: { questionJa: '冬の北海道はどうですか。', questionKana: 'ふゆのほっかいどうはどうですか。', questionKorean: '겨울 홋카이도는 어때요?', answerJa: '雪が多いです。', answerKana: 'ゆきがおおいです。', answerKorean: '눈이 많이 와요.' },
  w_kaze: { questionJa: '今日は寒いですね。何がありますか。', questionKana: 'きょうはさむいですね。なにがありますか。', questionKorean: '오늘 춥네요. 뭐가 불어요?', answerJa: '風が強いです。', answerKana: 'かぜがつよいです。', answerKorean: '바람이 세요.' },
  w_atsui: { questionJa: '夏の天気はどうですか。', questionKana: 'なつのてんきはどうですか。', questionKorean: '여름 날씨는 어때요?', answerJa: '暑いです。', answerKana: 'あついです。', answerKorean: '더워요.' },
  w_samui: { questionJa: '冬の天気はどうですか。', questionKana: 'ふゆのてんきはどうですか。', questionKorean: '겨울 날씨는 어때요?', answerJa: '寒いです。', answerKana: 'さむいです。', answerKorean: '추워요.' },
  w_suzushii: { questionJa: '秋の天気はどうですか。', questionKana: 'あきのてんきはどうですか。', questionKorean: '가을 날씨는 어때요?', answerJa: '涼しいです。', answerKana: 'すずしいです。', answerKorean: '시원해요.' },
  w_harunatsu: { questionJa: '日本には何がありますか。', questionKana: 'にほんにはなにがありますか。', questionKorean: '일본엔 뭐가 있어요?', answerJa: '春夏秋冬があります。', answerKana: 'しゅんかしゅうとうがあります。', answerKorean: '봄여름가을겨울(사계절)이 있어요.' },
  w_haru: { questionJa: '桜が咲く季節はいつですか。', questionKana: 'さくらがさくきせつはいつですか。', questionKorean: '벚꽃 피는 계절은 언제예요?', answerJa: '春です。', answerKana: 'はるです。', answerKorean: '봄이에요.' },
  w_natsu: { questionJa: '一番暑い季節はいつですか。', questionKana: 'いちばんあついきせつはいつですか。', questionKorean: '제일 더운 계절은 언제예요?', answerJa: '夏です。', answerKana: 'なつです。', answerKorean: '여름이에요.' },
  w_aki: { questionJa: '紅葉の季節はいつですか。', questionKana: 'こうようのきせつはいつですか。', questionKorean: '단풍 계절은 언제예요?', answerJa: '秋です。', answerKana: 'あきです。', answerKorean: '가을이에요.' },
  w_fuyu: { questionJa: '雪が降る季節はいつですか。', questionKana: 'ゆきがふるきせつはいつですか。', questionKorean: '눈 오는 계절은 언제예요?', answerJa: '冬です。', answerKana: 'ふゆです。', answerKorean: '겨울이에요.' },
  wea_101: { questionJa: '朝、遠くが見えませんね。', questionKana: 'あさ、とおくがみえませんね。', questionKorean: '아침에 멀리 안 보이네요.', answerJa: '霧ですね。', answerKana: 'きりですね。', answerKorean: '안개네요.' },
  wea_102: { questionJa: '空が光って、大きい音がしました。', questionKana: 'そらがひかって、おおきいおとがしました。', questionKorean: '하늘이 번쩍이고 큰 소리가 났어요.', answerJa: '雷ですね。', answerKana: 'かみなりですね。', answerKorean: '천둥이네요.' },
  wea_103: { questionJa: '台風が来ますね。', questionKana: 'たいふうがきますね。', questionKorean: '태풍이 오네요.', answerJa: '嵐になりそうです。', answerKana: 'あらしになりそうです。', answerKorean: '폭풍이 될 것 같아요.' },
  wea_104: { questionJa: '6月、日本の天気はどうですか。', questionKana: 'ろくがつ、にほんのてんきはどうですか。', questionKorean: '6월 일본 날씨는 어때요?', answerJa: '梅雨です。', answerKana: 'つゆです。', answerKorean: '장마철이에요.' },
  wea_105: { questionJa: '雨の後、空に何が出ましたか。', questionKana: 'あめのあと、そらになにがでましたか。', questionKorean: '비 온 뒤 하늘에 뭐가 나왔어요?', answerJa: '虹が出ました。', answerKana: 'にじがでました。', answerKorean: '무지개가 나왔어요.' },

  // ── 형용사 ────────────────────────────────────────────
  adj_1: { questionJa: 'この鞄はどうですか。', questionKana: 'このかばんはどうですか。', questionKorean: '이 가방은 어때요?', answerJa: '大きいです。', answerKana: 'おおきいです。', answerKorean: '커요.' },
  adj_2: { questionJa: 'この部屋はどうですか。', questionKana: 'このへやはどうですか。', questionKorean: '이 방은 어때요?', answerJa: '小さいです。', answerKana: 'ちいさいです。', answerKorean: '작아요.' },
  adj_3: { questionJa: 'このホテルはどうですか。', questionKana: 'このホテルはどうですか。', questionKorean: '이 호텔은 어때요?', answerJa: '高いです。', answerKana: 'たかいです。', answerKorean: '비싸요.' },
  adj_4: { questionJa: 'このお店はどうですか。', questionKana: 'このおみせはどうですか。', questionKorean: '이 가게는 어때요?', answerJa: '安いです。', answerKana: 'やすいです。', answerKorean: '싸요.' },
  adj_5: { questionJa: 'このスマホはどうですか。', questionKana: 'このスマホはどうですか。', questionKorean: '이 폰은 어때요?', answerJa: '新しいです。', answerKana: 'あたらしいです。', answerKorean: '새거예요.' },
  adj_6: { questionJa: 'このお寺はどうですか。', questionKana: 'このおてらはどうですか。', questionKorean: '이 절은 어때요?', answerJa: '古いです。', answerKana: 'ふるいです。', answerKorean: '오래됐어요.' },
  adj_7: { questionJa: 'この橋はどうですか。', questionKana: 'このはしはどうですか。', questionKorean: '이 다리는 어때요?', answerJa: '長いです。', answerKana: 'ながいです。', answerKorean: '길어요.' },
  adj_8: { questionJa: 'このスカートはどうですか。', questionKana: 'このスカートはどうですか。', questionKorean: '이 치마는 어때요?', answerJa: '短いです。', answerKana: 'みじかいです。', answerKorean: '짧아요.' },
  adj_9: { questionJa: '駅から家までどうですか。', questionKana: 'えきからいえまでどうですか。', questionKorean: '역에서 집까지 어때요?', answerJa: '近いです。', answerKana: 'ちかいです。', answerKorean: '가까워요.' },
  adj_10: { questionJa: '空港まではどうですか。', questionKana: 'くうこうまではどうですか。', questionKorean: '공항까지는 어때요?', answerJa: '遠いです。', answerKana: 'とおいです。', answerKorean: '멀어요.' },
  adj_11: { questionJa: '新幹線はどうですか。', questionKana: 'しんかんせんはどうですか。', questionKorean: '신칸센은 어때요?', answerJa: '早いです。', answerKana: 'はやいです。', answerKorean: '빨라요.' },
  adj_12: { questionJa: 'このバスはどうですか。', questionKana: 'このバスはどうですか。', questionKorean: '이 버스는 어때요?', answerJa: '遅いです。', answerKana: 'おそいです。', answerKorean: '느려요.' },
  adj_13: { questionJa: 'この映画はどうですか。', questionKana: 'このえいがはどうですか。', questionKorean: '이 영화 어때요?', answerJa: 'いいです。', answerKana: 'いいです。', answerKorean: '좋아요.' },
  adj_14: { questionJa: 'この天気はどうですか。', questionKana: 'このてんきはどうですか。', questionKorean: '이 날씨 어때요?', answerJa: '悪いです。', answerKana: 'わるいです。', answerKorean: '안 좋아요.' },
  adj_15: { questionJa: 'この店の客はどうですか。', questionKana: 'このみせのきゃくはどうですか。', questionKorean: '이 가게 손님은 어때요?', answerJa: '多いです。', answerKana: 'おおいです。', answerKorean: '많아요.' },
  adj_16: { questionJa: '今日の客はどうですか。', questionKana: 'きょうのきゃくはどうですか。', questionKorean: '오늘 손님은 어때요?', answerJa: '少ないです。', answerKana: 'すくないです。', answerKorean: '적어요.' },
  adj_17: { questionJa: 'この漢字はどうですか。', questionKana: 'このかんじはどうですか。', questionKorean: '이 한자 어때요?', answerJa: '難しいです。', answerKana: 'むずかしいです。', answerKorean: '어려워요.' },
  adj_18: { questionJa: 'このテストはどうですか。', questionKana: 'このテストはどうですか。', questionKorean: '이 시험 어때요?', answerJa: '易しいです。', answerKana: 'やさしいです。', answerKorean: '쉬워요.' },

  // ── 장소·시설 ──────────────────────────────────────────
  plc_1: { questionJa: 'すみません、飛行機はどこで乗りますか。', questionKana: 'すみません、ひこうきはどこでのりますか。', questionKorean: '저기요, 비행기는 어디서 타요?', answerJa: '空港です。', answerKana: 'くうこうです。', answerKorean: '공항이에요.' },
  plc_2: { questionJa: '今夜、どこに泊まりますか。', questionKana: 'こんや、どこにとまりますか。', questionKorean: '오늘 밤 어디서 자요?', answerJa: 'ホテルに泊まります。', answerKana: 'ホテルにとまります。', answerKorean: '호텔에서 자요.' },
  plc_3: { questionJa: '具合が悪いです。どこに行きますか。', questionKana: 'ぐあいがわるいです。どこにいきますか。', questionKorean: '몸이 안 좋아요. 어디로 가요?', answerJa: '病院に行きます。', answerKana: 'びょういんにいきます。', answerKorean: '병원에 가요.' },
  plc_4: { questionJa: 'お金を換えたいです。どこに行きますか。', questionKana: 'おかねをかえたいです。どこにいきますか。', questionKorean: '환전하고 싶어요. 어디로 가요?', answerJa: '銀行に行きます。', answerKana: 'ぎんこうにいきます。', answerKorean: '은행에 가요.' },
  plc_5: { questionJa: '手紙を出したいです。どこに行きますか。', questionKana: 'てがみをだしたいです。どこにいきますか。', questionKorean: '편지 부치고 싶어요. 어디로 가요?', answerJa: '郵便局に行きます。', answerKana: 'ゆうびんきょくにいきます。', answerKorean: '우체국에 가요.' },
  plc_6: { questionJa: '道が分かりません。どこで聞きますか。', questionKana: 'みちがわかりません。どこでききますか。', questionKorean: '길을 모르겠어요. 어디서 물어봐요?', answerJa: '交番で聞きます。', answerKana: 'こうばんでききます。', answerKorean: '파출소에서 물어봐요.' },
  plc_7: { questionJa: '子供とどこに行きますか。', questionKana: 'こどもとどこにいきますか。', questionKorean: '아이랑 어디로 가요?', answerJa: '公園に行きます。', answerKana: 'こうえんにいきます。', answerKorean: '공원에 가요.' },
  plc_8: { questionJa: '本を読みたいです。どこに行きますか。', questionKana: 'ほんをよみたいです。どこにいきますか。', questionKorean: '책 읽고 싶어요. 어디로 가요?', answerJa: '図書館に行きます。', answerKana: 'としょかんにいきます。', answerKorean: '도서관에 가요.' },
  plc_9: { questionJa: '映画を見たいです。どこに行きますか。', questionKana: 'えいがをみたいです。どこにいきますか。', questionKorean: '영화 보고 싶어요. 어디로 가요?', answerJa: '映画館に行きます。', answerKana: 'えいがかんにいきます。', answerKorean: '영화관에 가요.' },
  plc_10: { questionJa: '絵を見たいです。どこに行きますか。', questionKana: 'えをみたいです。どこにいきますか。', questionKorean: '그림 보고 싶어요. 어디로 가요?', answerJa: '美術館に行きます。', answerKana: 'びじゅつかんにいきます。', answerKorean: '미술관에 가요.' },
  plc_11: { questionJa: '疲れました。どこに行きたいですか。', questionKana: 'つかれました。どこにいきたいですか。', questionKorean: '피곤해요. 어디 가고 싶어요?', answerJa: '温泉に行きたいです。', answerKana: 'おんせんにいきたいです。', answerKorean: '온천에 가고 싶어요.' },
  plc_12: { questionJa: 'お正月、どこに行きますか。', questionKana: 'おしょうがつ、どこにいきますか。', questionKorean: '설날에 어디 가요?', answerJa: '神社に行きます。', answerKana: 'じんじゃにいきます。', answerKorean: '신사에 가요.' },
  plc_13: { questionJa: '京都で何を見ますか。', questionKana: 'きょうとでなにをみますか。', questionKorean: '교토에서 뭘 봐요?', answerJa: 'お寺を見ます。', answerKana: 'おてらをみます。', answerKorean: '절을 봐요.' },
  plc_14: { questionJa: '新鮮な魚はどこで買いますか。', questionKana: 'しんせんなさかなはどこでかいますか。', questionKorean: '신선한 생선은 어디서 사요?', answerJa: '市場で買います。', answerKana: 'いちばでかいます。', answerKorean: '시장에서 사요.' },
  plc_15: { questionJa: '財布に何がありますか。', questionKana: 'さいふになにがありますか。', questionKorean: '지갑에 뭐가 있어요?', answerJa: 'お金があります。', answerKana: 'おかねがあります。', answerKorean: '돈이 있어요.' },
  plc_16: { questionJa: '夕食はどこで食べますか。', questionKana: 'ゆうしょくはどこでたべますか。', questionKorean: '저녁은 어디서 먹어요?', answerJa: 'レストランで食べます。', answerKana: 'レストランでたべます。', answerKorean: '레스토랑에서 먹어요.' },
  plc_17: { questionJa: 'コンビニは遠いですか。', questionKana: 'コンビニはとおいですか。', questionKorean: '편의점은 멀어요?', answerJa: 'いいえ、近くです。', answerKana: 'いいえ、ちかくです。', answerKorean: '아니요, 근처예요.' },

  // ── 교통수단 ───────────────────────────────────────────
  trp_1: { questionJa: '何で会社に行きますか。', questionKana: 'なんでかいしゃにいきますか。', questionKorean: '뭘로 회사에 가요?', answerJa: '電車で行きます。', answerKana: 'でんしゃでいきます。', answerKorean: '전철로 가요.' },
  trp_2: { questionJa: '東京の中はよく何に乗りますか。', questionKana: 'とうきょうのなかはよくなににのりますか。', questionKorean: '도쿄 시내는 뭘 자주 타요?', answerJa: '地下鉄に乗ります。', answerKana: 'ちかてつにのります。', answerKorean: '지하철을 타요.' },
  trp_3: { questionJa: '大阪まで何で行きますか。', questionKana: 'おおさかまでなんでいきますか。', questionKorean: '오사카까지 뭘로 가요?', answerJa: '新幹線で行きます。', answerKana: 'しんかんせんでいきます。', answerKorean: '신칸센으로 가요.' },
  trp_4: { questionJa: '空港までどうやって行きますか。', questionKana: 'くうこうまでどうやっていきますか。', questionKorean: '공항까지 어떻게 가요?', answerJa: 'バスで行きます。', answerKana: 'バスでいきます。', answerKorean: '버스로 가요.' },
  trp_5: { questionJa: '荷物が多いです。何で行きますか。', questionKana: 'にもつがおおいです。なんでいきますか。', questionKorean: '짐이 많아요. 뭘로 가요?', answerJa: 'タクシーで行きます。', answerKana: 'タクシーでいきます。', answerKorean: '택시로 가요.' },
  trp_6: { questionJa: '海外にはどうやって行きますか。', questionKana: 'かいがいにはどうやっていきますか。', questionKorean: '해외는 어떻게 가요?', answerJa: '飛行機で行きます。', answerKana: 'ひこうきでいきます。', answerKorean: '비행기로 가요.' },
  trp_7: { questionJa: '近い所にはどうやって行きますか。', questionKana: 'ちかいところにはどうやっていきますか。', questionKorean: '가까운 곳은 어떻게 가요?', answerJa: '自転車で行きます。', answerKana: 'じてんしゃでいきます。', answerKorean: '자전거로 가요.' },
  trp_8: { questionJa: '家族旅行、何で行きますか。', questionKana: 'かぞくりょこう、なんでいきますか。', questionKorean: '가족 여행, 뭘로 가요?', answerJa: '車で行きます。', answerKana: 'くるまでいきます。', answerKorean: '차로 가요.' },
  trp_9: { questionJa: '島まで何で行きますか。', questionKana: 'しままでなんでいきますか。', questionKorean: '섬까지 뭘로 가요?', answerJa: '船で行きます。', answerKana: 'ふねでいきます。', answerKorean: '배로 가요.' },
  trp_10: { questionJa: '空港と町を結ぶ電車は何ですか。', questionKana: 'くうこうとまちをむすぶでんしゃはなんですか。', questionKorean: '공항이랑 시내를 잇는 전철은 뭐예요?', answerJa: 'モノレールです。', answerKana: 'モノレールです。', answerKorean: '모노레일이에요.' },

  // ── 감정·상태 ──────────────────────────────────────────
  fel_1: { questionJa: 'プレゼントをもらいました。今どうですか。', questionKana: 'プレゼントをもらいました。いまどうですか。', questionKorean: '선물 받았어요. 지금 어때요?', answerJa: '嬉しいです。', answerKana: 'うれしいです。', answerKorean: '기뻐요.' },
  fel_2: { questionJa: '友達と別れました。今どうですか。', questionKana: 'ともだちとわかれました。いまどうですか。', questionKorean: '친구랑 헤어졌어요. 지금 어때요?', answerJa: '悲しいです。', answerKana: 'かなしいです。', answerKorean: '슬퍼요.' },
  fel_3: { questionJa: '旅行はどうでしたか。', questionKana: 'りょこうはどうでしたか。', questionKorean: '여행 어땠어요?', answerJa: '楽しかったです。', answerKana: 'たのしかったです。', answerKorean: '즐거웠어요.' },
  fel_4: { questionJa: 'ホラー映画を見ました。どうでしたか。', questionKana: 'ホラーえいがをみました。どうでしたか。', questionKorean: '공포 영화 봤어요. 어땠어요?', answerJa: '怖かったです。', answerKana: 'こわかったです。', answerKorean: '무서웠어요.' },
  fel_5: { questionJa: '仕事の後、どうですか。', questionKana: 'しごとのあと、どうですか。', questionKorean: '일 끝나고 어때요?', answerJa: '疲れました。', answerKana: 'つかれました。', answerKorean: '피곤해요.' },
  fel_6: { questionJa: '夜遅いですね。今どうですか。', questionKana: 'よるおそいですね。いまどうですか。', questionKorean: '밤늦었네요. 지금 어때요?', answerJa: '眠いです。', answerKana: 'ねむいです。', answerKorean: '졸려요.' },
  fel_7: { questionJa: '朝ご飯を食べていません。今どうですか。', questionKana: 'あさごはんをたべていません。いまどうですか。', questionKorean: '아침을 안 먹었어요. 지금 어때요?', answerJa: 'お腹すいた。', answerKana: 'おなかすいた。', answerKorean: '배고파요.' },
  fel_8: { questionJa: '最近、仕事はどうですか。', questionKana: 'さいきん、しごとはどうですか。', questionKorean: '요즘 일은 어때요?', answerJa: '忙しいです。', answerKana: 'いそがしいです。', answerKorean: '바빠요.' },
  fel_9: { questionJa: 'お元気ですか。', questionKana: 'おげんきですか。', questionKorean: '잘 지내세요?', answerJa: 'はい、元気です。', answerKana: 'はい、げんきです。', answerKorean: '네, 건강해요.' },
  fel_10: { questionJa: '大丈夫ですか。', questionKana: 'だいじょうぶですか。', questionKorean: '괜찮아요?', answerJa: 'はい、大丈夫です。', answerKana: 'はい、だいじょうぶです。', answerKorean: '네, 괜찮아요.' },
  fel_11: { questionJa: 'どうしましたか。', questionKana: 'どうしましたか。', questionKorean: '무슨 일이에요?', answerJa: 'お腹が痛いです。', answerKana: 'おなかがいたいです。', answerKorean: '배가 아파요.' },
  fel_12: { questionJa: '一人暮らしはどうですか。', questionKana: 'ひとりぐらしはどうですか。', questionKorean: '자취는 어때요?', answerJa: '時々寂しいです。', answerKana: 'ときどきさびしいです。', answerKorean: '가끔 외로워요.' },
};

export function vocabExampleFor(id: string): VocabExample | undefined {
  return VOCAB_EXAMPLES[id];
}
